using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BackendFramework.Interfaces;
using BackendFramework.Models;
using BackendFramework.Otel;

namespace BackendFramework.Services
{
    /// <summary> More complex functions and application logic for <see cref="Word"/>s </summary>
    public class WordService(IWordRepository wordRepo) : IWordService
    {
        private readonly IWordRepository _wordRepo = wordRepo;

        private const string otelTagName = "otel.WordService";

        /// <summary>
        /// Clear the given word's Id and Metadata to be generated by the word repo,
        /// and add the given userId to EditedBy if it's not already last on the list.
        /// </summary>
        private static Word PrepEditedData(string userId, Word word)
        {
            word.Id = "";
            word.Modified = "";
            if (!string.IsNullOrWhiteSpace(userId) && userId != word.EditedBy.LastOrDefault(""))
            {
                word.EditedBy.Add(userId);
            }
            return word;
        }

        /// <summary> Creates a new word with updated edited data. </summary>
        /// <returns> The created word </returns>
        public async Task<Word> Create(string userId, Word word)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "creating a word");

            return await _wordRepo.Create(PrepEditedData(userId, word));
        }

        /// <summary> Creates new words with updated edited data. </summary>
        /// <returns> The created word </returns>
        public async Task<List<Word>> Create(string userId, List<Word> words)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "creating words");

            return await _wordRepo.Create(words.Select(w => PrepEditedData(userId, w)).ToList());
        }

        /// <summary> Adds a new word with updated edited data. </summary>
        /// <returns> The added word </returns>
        private async Task<Word> Add(string userId, Word word)
        {
            return await _wordRepo.Add(PrepEditedData(userId, word));
        }

        /// <summary> Removes audio with specified fileName from a word </summary>
        /// <returns> A string: id of updated word, or null if not found </returns>
        public async Task<string?> DeleteAudio(string projectId, string userId, string wordId, string fileName)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "deleting an audio");

            // We only want to update words that are in the frontier
            var wordWithAudioToDelete = (await _wordRepo.GetFrontier(projectId, wordId, fileName))?.Clone();
            if (wordWithAudioToDelete is null)
            {
                return null;
            }

            wordWithAudioToDelete.Audio.RemoveAll(a => a.FileName == fileName);
            return (await Update(userId, wordWithAudioToDelete))?.Id;
        }

        /// <summary> Removes word from Frontier and adds a Deleted copy in the word collection </summary>
        /// <returns> A string: id of Deleted word </returns>
        public async Task<string?> DeleteFrontierWord(string projectId, string userId, string wordId)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "deleting a word from Frontier");

            var word = (await _wordRepo.GetFrontier(projectId, wordId))?.Clone();
            if (word is null)
            {
                return null;
            }

            word.ProjectId = projectId;
            word.Accessibility = Status.Deleted;
            word.History.Add(wordId);

            var deletedWord = await Add(userId, word);

            // Don't remove the Frontier word until the copy is successfully stored as deleted.
            await _wordRepo.DeleteFrontier(projectId, wordId);

            return deletedWord.Id;
        }

        /// <summary> Tries to remove words from Frontier and add Deleted copies in the word collection </summary>
        /// <returns> An int: number of successful deletions </returns>
        public async Task<int> TryDeleteFrontierWords(string projectId, string userId, List<string> wordIds)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "deleting words from Frontier");

            var deletedCount = 0;
            foreach (var wordId in wordIds)
            {
                try
                {
                    if (await DeleteFrontierWord(projectId, userId, wordId) is not null)
                    {
                        deletedCount++;
                    }
                }
                catch
                {
                    Console.WriteLine($"Failed to delete word with id {wordId} from Frontier");
                }
            }
            return deletedCount;
        }

        /// <summary> Restore a word to the Frontier </summary>
        /// <returns> A bool: true if restored; false if already in frontier or word not found </returns>
        public async Task<bool> RestoreToFrontier(string projectId, string wordId)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "restoring a word to Frontier");

            if (await _wordRepo.IsInFrontier(projectId, wordId))
            {
                return false;
            }

            var word = (await _wordRepo.GetWord(projectId, wordId))?.Clone();
            if (word is null)
            {
                return false;
            }

            await _wordRepo.AddFrontier(word);
            return true;
        }

        /// <summary> Restores words to the Frontier that aren't in the Frontier </summary>
        /// <returns> A bool: true if all successfully restored. </returns>
        public async Task<bool> RestoreToFrontier(string projectId, List<string> wordIds)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "restoring words to Frontier");

            wordIds = wordIds.Distinct().ToList();

            // Make sure all the words exist but not in the Frontier
            if (!await _wordRepo.AreNonFrontierWords(projectId, wordIds))
            {
                return false;
            }

            // Restore each word
            foreach (var id in wordIds)
            {
                if (!await RestoreToFrontier(projectId, id))
                {
                    Console.WriteLine($"Failed to restore word with id {id} to Frontier of project {projectId}");
                    return false;
                }
            }

            return true;
        }

        /// <summary> Makes a new word in the Frontier with changes made </summary>
        /// <returns> Updated word, or null if word-to-update not found </returns>
        public async Task<Word?> Update(string userId, Word word)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "updating a word in Frontier");

            var oldWordId = word.Id;
            var oldWord = await _wordRepo.GetFrontier(word.ProjectId, oldWordId);
            if (oldWord is null)
            {
                return null;
            }

            word.Created = oldWord.Created;
            if (!word.History.Contains(oldWordId))
            {
                word.History.Add(oldWordId);
            }
            // If an imported word was using the citation form for its Vernacular,
            // only keep UsingCitationForm true if the Vernacular hasn't changed.
            word.UsingCitationForm &= word.Vernacular == oldWord.Vernacular;

            var newWord = await Create(userId, word);

            // Don't remove the old Frontier word until the new word is successfully created.
            await _wordRepo.DeleteFrontier(word.ProjectId, oldWordId);

            return newWord;
        }

        /// <summary> Checks if a word being added is a duplicate of a preexisting word. </summary>
        /// <returns> The id string of the existing word, or null if none. </returns>
        public async Task<string?> FindContainingWord(Word word)
        {
            using var activity = OtelService.StartActivityWithTag(otelTagName, "checking for duplicates of a word");

            var wordsWithVern = await _wordRepo.GetFrontierWithVernacular(word.ProjectId, word.Vernacular);
            var duplicatedWord = wordsWithVern.Find(w => w.Contains(word));
            return duplicatedWord?.Id;
        }
    }
}
