name: "Combine Deploy Updates"
description: "Deploy updated Helm charts for The Combine to the Kubernetes cluster"
inputs:
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_account:
    description: "AWS Account ID"
    required: true
  aws_default_region:
    description: "AWS Default Region"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  combine_captcha_secret_key:
    description: "Cloudflare Turnstile secret key for The Combine"
    required: true
  combine_jwt_secret_key:
    description: "JWT secret key for The Combine"
    required: true
  combine_smtp_password:
    description: "SMTP password for sending emails from The Combine"
    required: true
  combine_smtp_username:
    description: "SMTP username for sending emails from The Combine"
    required: true
  helm_version:
    description: "Version of helm to install on the runner"
    required: true
  image_registry:
    description: "Docker Image Registry (full path, e.g. public.ecr.aws/thecombine)"
    required: true
  image_tag:
    description: "Image Tag for docker images"
    required: true
  kube_context:
    description: "Context for the kubectl/helm commands"
    required: true
  kubectl_version:
    description: "Version of kubectl to install on the runner"
    required: true
  target:
    description: "Deployment target as defined in deploy/scripts/setup_files/combine_config.yaml (e.g. qa, prod)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Helm
      run: |
        echo "Installing Helm version ${{ inputs.helm_version }}"
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | DESIRED_VERSION=${{ inputs.helm_version }} bash
        helm version
      shell: bash

    - name: Install kubectl
      run: |
        cd
        echo "Installing kubectl version ${{ inputs.kubectl_version }}"
        curl -LO https://dl.k8s.io/release/${{ inputs.kubectl_version }}/bin/linux/amd64/kubectl
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --output=yaml
      shell: bash

    - name: Install Python requirements
      run: python3 -m pip install -r deploy/requirements.txt
      shell: bash

    - name: Deploy with Helm
      run: >
        deploy/scripts/setup_combine.py
        --context ${{ inputs.kube_context }}
        --repo ${{ inputs.image_registry }}
        --tag ${{ inputs.image_tag }}
        --target ${{ inputs.target }}
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_ACCOUNT: ${{ inputs.aws_account }}
        AWS_DEFAULT_REGION: ${{ inputs.aws_default_region }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        COMBINE_CAPTCHA_SECRET_KEY: ${{ inputs.combine_captcha_secret_key }}
        COMBINE_JWT_SECRET_KEY: ${{ inputs.combine_jwt_secret_key }}
        COMBINE_SMTP_PASSWORD: ${{ inputs.combine_smtp_password }}
        COMBINE_SMTP_USERNAME: ${{ inputs.combine_smtp_username }}
