name: "Combine Deploy Updates"
description: "Deploy updated images for The Combine to the Kubernetes cluster"
inputs:
  helm_version:
    description: "Version of helm to install on the runner"
    required: true
  image_registry:
    description: "Docker Image Registry"
    required: true
  image_registry_alias:
    description: >
      Custom or default alias for AWS Public ECR registries.  Blank for AWS ECR Private registries.
      If the image_registry_alias is specified, include the '/' at the beginning of the string,
      e.g. /thecombine
    required: false
    default: ""
  image_tag:
    description: "Image Tag for docker images"
    required: true
  kube_context:
    description: "Context for the kubectl commands"
    required: true
  kubectl_version:
    description: "Version of kubectl to install on the runner"
    required: true
  update_cert_proxy:
    description: "Specification for whether the combine-cert-proxy should be updated."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Helm
      run: |
        echo "Installing Helm version ${{ inputs.helm_version }}"
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | DESIRED_VERSION=${{ inputs.helm_version }} bash
        helm version
      shell: bash

    - name: Install kubectl
      run: |
        cd
        echo "Installing kubectl version ${{ inputs.kubectl_version }}"
        curl -LO https://dl.k8s.io/release/${{ inputs.kubectl_version }}/bin/linux/amd64/kubectl
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --output=yaml
      shell: bash

    - name: Deploy images via Helm
      run: |
        echo "Updating images with version ${{ inputs.image_tag }}"
        helm upgrade thecombine ./deploy/helm/thecombine \
          --install \
          --namespace thecombine \
          --kube-context ${{ inputs.kube_context }} \
          --set global.imageTag="${{ inputs.image_tag }}" \
          --set global.imageRegistry="${{ inputs.image_registry }}${{ inputs.image_registry_alias }}" \
          --wait \
          --timeout 10m
      shell: bash

    - name: Update Cert Proxy Server via kubectl
      if: ${{ inputs.update_cert_proxy == 'true' }}
      run: |
        echo "Updating cert-proxy with version ${{ inputs.image_tag }}"
        kubectl --context ${{ inputs.kube_context }} \
          --namespace combine-cert-proxy \
          set image deployment/combine-cert-proxy \
          combine-cert-proxy="${{ inputs.image_registry }}${{ inputs.image_registry_alias }}/combine_maint:${{ inputs.image_tag }}"
      shell: bash
