#! /bin/bash

# fix the baseURL for the React UI
cd ${HOME}/src/TheCombine/src/backend
sed -i s/baseURL: "https:\/\/localhost:5001\/v1"/baseURL: "https:\/\/thewordcombine.org\/v1"/ index.tsx
cd ${HOME}/src/TheCombine/deploy
./setup-target.sh -b vagrant@localhost
