[flake8]
max-line-length = 99
extend-ignore = E203
extend-exclude = .mypy_cache, node_modules, venv

[gh-actions]
python =
    3.12: lint, fmt-check, type-check, user-guide

[tox]
envlist =
    fmt-check
    lint
    type-check
    user-guide
skipsdist = true

[testenv]
deps =
    -r{toxinidir}/dev-requirements.txt
basepython = 3.12

[testenv:type-check]
commands =
    mypy deploy scripts
    mypy --platform linux maintenance/scripts

[testenv:lint]
commands =
    flake8

[testenv:fmt]
commands =
    isort .
    black .

[testenv:fmt-check]
commands =
    isort --check .
    black --check .

[testenv:user-guide]
changedir = {toxinidir}/docs/user_guide/
commands =
    mkdocs build

[testenv:user-guide-serve]
changedir = {toxinidir}/docs/user_guide/
commands =
    mkdocs serve

[testenv:user-guide-github-pages]
changedir = {toxinidir}/docs/user_guide/
commands =
    # See: https://squidfunk.github.io/mkdocs-material/publishing-your-site/
    mkdocs gh-deploy --force
