// This file was generated by `python scripts/split_dictionary.py -l ru -t 2500 -T 25000 -m 7`.

const cases = [
  "1072",
  "1073",
  "1074",
  "1075",
  "1076",
  "1079",
  "1080",
  "1082",
  "1083",
  "1084",
  "1085",
  "1086",
  "1087",
  "1088",
  "1089",
  "1090",
  "1091",
  "1092",
  "1093",
  "1096",
]

export default async function (start?: string, exclude?: string[]): Promise<[string?,string?]> {
  if (!start) {
    return ["", (await import("resources/dictionaries/ru/u.dic")).default];
  }

  const startCase = start.split("").map(c=>c.toLocaleLowerCase().charCodeAt(0))
  var startCode = startCase.join("-")
  while (startCode){
    if (cases.includes(startCode)){
      break
    }
    startCase.pop()
    startCode = startCase.join("-")
  }

  if (!startCode || exclude?.includes(startCode)) {
    return [undefined, undefined]
  }

  switch (startCode) {
    case "1072":
      return [startCode, (await import("resources/dictionaries/ru/u1072.dic")).default];
    case "1073":
      return [startCode, (await import("resources/dictionaries/ru/u1073.dic")).default];
    case "1074":
      return [startCode, (await import("resources/dictionaries/ru/u1074.dic")).default];
    case "1075":
      return [startCode, (await import("resources/dictionaries/ru/u1075.dic")).default];
    case "1076":
      return [startCode, (await import("resources/dictionaries/ru/u1076.dic")).default];
    case "1079":
      return [startCode, (await import("resources/dictionaries/ru/u1079.dic")).default];
    case "1080":
      return [startCode, (await import("resources/dictionaries/ru/u1080.dic")).default];
    case "1082":
      return [startCode, (await import("resources/dictionaries/ru/u1082.dic")).default];
    case "1083":
      return [startCode, (await import("resources/dictionaries/ru/u1083.dic")).default];
    case "1084":
      return [startCode, (await import("resources/dictionaries/ru/u1084.dic")).default];
    case "1085":
      return [startCode, (await import("resources/dictionaries/ru/u1085.dic")).default];
    case "1086":
      return [startCode, (await import("resources/dictionaries/ru/u1086.dic")).default];
    case "1087":
      return [startCode, (await import("resources/dictionaries/ru/u1087.dic")).default];
    case "1088":
      return [startCode, (await import("resources/dictionaries/ru/u1088.dic")).default];
    case "1089":
      return [startCode, (await import("resources/dictionaries/ru/u1089.dic")).default];
    case "1090":
      return [startCode, (await import("resources/dictionaries/ru/u1090.dic")).default];
    case "1091":
      return [startCode, (await import("resources/dictionaries/ru/u1091.dic")).default];
    case "1092":
      return [startCode, (await import("resources/dictionaries/ru/u1092.dic")).default];
    case "1093":
      return [startCode, (await import("resources/dictionaries/ru/u1093.dic")).default];
    case "1096":
      return [startCode, (await import("resources/dictionaries/ru/u1096.dic")).default];
    default:
      return [undefined, undefined];
    }
}
