// This file was generated by `python scripts/split_dictionary.py -l hi -t 500`.

export default async function (letter?: string, exclude?: string[]) {
  if (!letter) {
    return (await import("resources/dictionaries/hi/u.dic")).default;
  }

  const code = letter.toLocaleLowerCase()[0].charCodeAt(0);
  const excludeCodes = exclude?.map(l => l.toLocaleLowerCase()[0].charCodeAt(0))
  if (excludeCodes?.includes(code)) {
    return;
  }

  switch (code) {
    case 2309:
      return (await import("resources/dictionaries/hi/u2309.dic")).default;
    case 2325:
      return (await import("resources/dictionaries/hi/u2325.dic")).default;
    case 2327:
      return (await import("resources/dictionaries/hi/u2327.dic")).default;
    case 2332:
      return (await import("resources/dictionaries/hi/u2332.dic")).default;
    case 2342:
      return (await import("resources/dictionaries/hi/u2342.dic")).default;
    case 2344:
      return (await import("resources/dictionaries/hi/u2344.dic")).default;
    case 2346:
      return (await import("resources/dictionaries/hi/u2346.dic")).default;
    case 2348:
      return (await import("resources/dictionaries/hi/u2348.dic")).default;
    case 2350:
      return (await import("resources/dictionaries/hi/u2350.dic")).default;
    case 2352:
      return (await import("resources/dictionaries/hi/u2352.dic")).default;
    case 2357:
      return (await import("resources/dictionaries/hi/u2357.dic")).default;
    case 2360:
      return (await import("resources/dictionaries/hi/u2360.dic")).default;
    case 2361:
      return (await import("resources/dictionaries/hi/u2361.dic")).default;
    default:
      return;
    }
}
