// This file was generated by `python scripts/split_dictionary.py -l hi -m -1 -t 1000 -T 20000`.

export const keys = ["2325", "2346", "2348", "2350", "2360"];

export default async function (key?: string): Promise<string | undefined> {
  if (!key) {
    return (await import("resources/dictionaries/hi/u.dic")).default;
  }

  switch (key) {
    case "2325":
      return (await import("resources/dictionaries/hi/u2325.dic")).default;
    case "2346":
      return (await import("resources/dictionaries/hi/u2346.dic")).default;
    case "2348":
      return (await import("resources/dictionaries/hi/u2348.dic")).default;
    case "2350":
      return (await import("resources/dictionaries/hi/u2350.dic")).default;
    case "2360":
      return (await import("resources/dictionaries/hi/u2360.dic")).default;
    default:
      return;
  }
}
