// This file was generated by `python scripts/split_dictionary.py -l hi -t 700 -T 35000`.

const cases = [
  "2309",
  "2325",
  "2332",
  "2346",
  "2348",
  "2350",
  "2360",
]

export default async function (start?: string, exclude?: string[]): Promise<[string?,string?]> {
  if (!start) {
    return ["", (await import("resources/dictionaries/hi/u.dic")).default];
  }

  const startCase = start.split("").map(c=>c.toLocaleLowerCase().charCodeAt(0))
  var startCode = startCase.join("-")
  while (startCode){
    if (cases.includes(startCode)){
      break
    }
    startCase.pop()
    startCode = startCase.join("-")
  }

  if (!startCode || exclude?.includes(startCode)) {
    return [undefined, undefined]
  }

  switch (startCode) {
    case "2309":
      return [startCode, (await import("resources/dictionaries/hi/u2309.dic")).default];
    case "2325":
      return [startCode, (await import("resources/dictionaries/hi/u2325.dic")).default];
    case "2332":
      return [startCode, (await import("resources/dictionaries/hi/u2332.dic")).default];
    case "2346":
      return [startCode, (await import("resources/dictionaries/hi/u2346.dic")).default];
    case "2348":
      return [startCode, (await import("resources/dictionaries/hi/u2348.dic")).default];
    case "2350":
      return [startCode, (await import("resources/dictionaries/hi/u2350.dic")).default];
    case "2360":
      return [startCode, (await import("resources/dictionaries/hi/u2360.dic")).default];
    default:
      return [undefined, undefined];
    }
}
