// This file was generated by `python scripts/split_dictionary.py -l ar -t 1000`.

export default async function (letter?: string, exclude?: string[]) {
  if (!letter) {
    return (await import("resources/dictionaries/ar/u.dic")).default;
  }

  const code = letter.toLocaleLowerCase()[0].charCodeAt(0);
  const excludeCodes = exclude?.map(l => l.toLocaleLowerCase()[0].charCodeAt(0))
  if (excludeCodes?.includes(code)) {
    return;
  }

  switch (code) {
    case 1576:
      return (await import("resources/dictionaries/ar/u1576.dic")).default;
    case 1608:
      return (await import("resources/dictionaries/ar/u1608.dic")).default;
    case 1601:
      return (await import("resources/dictionaries/ar/u1601.dic")).default;
    case 1587:
      return (await import("resources/dictionaries/ar/u1587.dic")).default;
    case 1594:
      return (await import("resources/dictionaries/ar/u1594.dic")).default;
    case 1603:
      return (await import("resources/dictionaries/ar/u1603.dic")).default;
    case 1604:
      return (await import("resources/dictionaries/ar/u1604.dic")).default;
    case 1571:
      return (await import("resources/dictionaries/ar/u1571.dic")).default;
    case 1605:
      return (await import("resources/dictionaries/ar/u1605.dic")).default;
    case 1581:
      return (await import("resources/dictionaries/ar/u1581.dic")).default;
    case 1578:
      return (await import("resources/dictionaries/ar/u1578.dic")).default;
    case 1584:
      return (await import("resources/dictionaries/ar/u1584.dic")).default;
    case 1607:
      return (await import("resources/dictionaries/ar/u1607.dic")).default;
    case 1573:
      return (await import("resources/dictionaries/ar/u1573.dic")).default;
    case 1580:
      return (await import("resources/dictionaries/ar/u1580.dic")).default;
    case 1588:
      return (await import("resources/dictionaries/ar/u1588.dic")).default;
    case 1606:
      return (await import("resources/dictionaries/ar/u1606.dic")).default;
    case 1589:
      return (await import("resources/dictionaries/ar/u1589.dic")).default;
    case 1591:
      return (await import("resources/dictionaries/ar/u1591.dic")).default;
    case 1593:
      return (await import("resources/dictionaries/ar/u1593.dic")).default;
    case 1583:
      return (await import("resources/dictionaries/ar/u1583.dic")).default;
    case 1585:
      return (await import("resources/dictionaries/ar/u1585.dic")).default;
    case 1575:
      return (await import("resources/dictionaries/ar/u1575.dic")).default;
    case 1582:
      return (await import("resources/dictionaries/ar/u1582.dic")).default;
    case 1586:
      return (await import("resources/dictionaries/ar/u1586.dic")).default;
    case 1590:
      return (await import("resources/dictionaries/ar/u1590.dic")).default;
    case 1602:
      return (await import("resources/dictionaries/ar/u1602.dic")).default;
    case 1610:
      return (await import("resources/dictionaries/ar/u1610.dic")).default;
    default:
      return;
    }
}
