#!/usr/bin/perl

############################################################
# This script allows one to redefine the links from the
# letsencrypt live directory to a different version in the
# archive directory.  It is designed as a debugging aid.
#
# ! ! N O T   F O R   P R O D U C T I O N   U S E ! !
#
############################################################

use strict;

my $newLink='';
my $serverName="thecombine.languagetechnology.org";
while ($#ARGV > -1)
{
  my $opt = shift;
  if ($opt =~ /^([0-9]+)$/)
  {
    $newLink = $1;
  }
  elsif ($opt == "--server"){
    $serverName = shift;
  }
}

$newLink or die "Missing certificate number for the new link.";
print STDOUT "New link: $newLink\n";

my @certFiles = ( "cert", "chain", "fullchain", "privkey");
chdir "/etc/letsencrypt/live/$serverName";
foreach my $cFile ( @certFiles )
{
  my $linkName = "$cFile.pem";
  my $linkTarget = "../../archive/$serverName/$cFile$newLink.pem";
  if ( -l $linkName)
  {
    print STDERR "Unlinking $linkName\n";
    unlink $linkName;
    print STDERR "Linking $linkName to $linkTarget\n";
    symlink $linkTarget, $linkName;
  }
}
