// This file was generated by `python scripts/split_dictionary.py -l en -m -1 -t 2000 -T 20000`.

import { fetchText } from "utilities/fontCssUtilities";

export const keys = [
  "97",
  "98",
  "99",
  "100",
  "101",
  "102",
  "103",
  "104",
  "105",
  "108",
  "109",
  "110",
  "111",
  "112",
  "114",
  "115",
  "116",
  "117",
  "119",
];

export default async function (key?: string): Promise<string | undefined> {
  if (!key) {
    return await fetchText("/dictionaries/en/u.dic");
  }

  switch (key) {
    case "97":
      return await fetchText("/dictionaries/en/u97.dic");
    case "98":
      return await fetchText("/dictionaries/en/u98.dic");
    case "99":
      return await fetchText("/dictionaries/en/u99.dic");
    case "100":
      return await fetchText("/dictionaries/en/u100.dic");
    case "101":
      return await fetchText("/dictionaries/en/u101.dic");
    case "102":
      return await fetchText("/dictionaries/en/u102.dic");
    case "103":
      return await fetchText("/dictionaries/en/u103.dic");
    case "104":
      return await fetchText("/dictionaries/en/u104.dic");
    case "105":
      return await fetchText("/dictionaries/en/u105.dic");
    case "108":
      return await fetchText("/dictionaries/en/u108.dic");
    case "109":
      return await fetchText("/dictionaries/en/u109.dic");
    case "110":
      return await fetchText("/dictionaries/en/u110.dic");
    case "111":
      return await fetchText("/dictionaries/en/u111.dic");
    case "112":
      return await fetchText("/dictionaries/en/u112.dic");
    case "114":
      return await fetchText("/dictionaries/en/u114.dic");
    case "115":
      return await fetchText("/dictionaries/en/u115.dic");
    case "116":
      return await fetchText("/dictionaries/en/u116.dic");
    case "117":
      return await fetchText("/dictionaries/en/u117.dic");
    case "119":
      return await fetchText("/dictionaries/en/u119.dic");
    default:
      return;
  }
}
