// This file was generated by `python scripts/split_dictionary.py -l pt -m 7 -t 2000 -T 20000`.

import { fetchText } from "utilities/fontCssUtilities";

export const keys = [
  "97",
  "97-98",
  "97-99",
  "97-108",
  "97-114",
  "98",
  "99",
  "100",
  "101",
  "102",
  "103",
  "105",
  "106",
  "108",
  "109",
  "110",
  "111",
  "112",
  "114",
  "115",
  "116",
  "117",
  "118",
];

export default async function (key?: string): Promise<string | undefined> {
  if (!key) {
    return await fetchText("/dictionaries/pt/u.dic");
  }

  switch (key) {
    case "97":
      return await fetchText("/dictionaries/pt/u97.dic");
    case "97-98":
      return await fetchText("/dictionaries/pt/u97-98.dic");
    case "97-99":
      return await fetchText("/dictionaries/pt/u97-99.dic");
    case "97-108":
      return await fetchText("/dictionaries/pt/u97-108.dic");
    case "97-114":
      return await fetchText("/dictionaries/pt/u97-114.dic");
    case "98":
      return await fetchText("/dictionaries/pt/u98.dic");
    case "99":
      return await fetchText("/dictionaries/pt/u99.dic");
    case "100":
      return await fetchText("/dictionaries/pt/u100.dic");
    case "101":
      return await fetchText("/dictionaries/pt/u101.dic");
    case "102":
      return await fetchText("/dictionaries/pt/u102.dic");
    case "103":
      return await fetchText("/dictionaries/pt/u103.dic");
    case "105":
      return await fetchText("/dictionaries/pt/u105.dic");
    case "106":
      return await fetchText("/dictionaries/pt/u106.dic");
    case "108":
      return await fetchText("/dictionaries/pt/u108.dic");
    case "109":
      return await fetchText("/dictionaries/pt/u109.dic");
    case "110":
      return await fetchText("/dictionaries/pt/u110.dic");
    case "111":
      return await fetchText("/dictionaries/pt/u111.dic");
    case "112":
      return await fetchText("/dictionaries/pt/u112.dic");
    case "114":
      return await fetchText("/dictionaries/pt/u114.dic");
    case "115":
      return await fetchText("/dictionaries/pt/u115.dic");
    case "116":
      return await fetchText("/dictionaries/pt/u116.dic");
    case "117":
      return await fetchText("/dictionaries/pt/u117.dic");
    case "118":
      return await fetchText("/dictionaries/pt/u118.dic");
    default:
      return;
  }
}
