// This file was generated by `python scripts/split_dictionary.py -l sw -m -1 -t 2000 -T 20000`.

import { fetchText } from "utilities/fontCssUtilities";

export const keys = [
  "97",
  "104",
  "105",
  "107",
  "109",
  "110",
  "115",
  "116",
  "117",
  "119",
];

export default async function (key?: string): Promise<string | undefined> {
  if (!key) {
    return await fetchText("/dictionaries/sw/u.dic");
  }

  switch (key) {
    case "97":
      return await fetchText("/dictionaries/sw/u97.dic");
    case "104":
      return await fetchText("/dictionaries/sw/u104.dic");
    case "105":
      return await fetchText("/dictionaries/sw/u105.dic");
    case "107":
      return await fetchText("/dictionaries/sw/u107.dic");
    case "109":
      return await fetchText("/dictionaries/sw/u109.dic");
    case "110":
      return await fetchText("/dictionaries/sw/u110.dic");
    case "115":
      return await fetchText("/dictionaries/sw/u115.dic");
    case "116":
      return await fetchText("/dictionaries/sw/u116.dic");
    case "117":
      return await fetchText("/dictionaries/sw/u117.dic");
    case "119":
      return await fetchText("/dictionaries/sw/u119.dic");
    default:
      return;
  }
}
