// This file was generated by `python scripts/split_dictionary.py -l en -t 2000 -T 20000 -m -1`.

export const keys = [
  "97",
  "98",
  "99",
  "100",
  "101",
  "102",
  "103",
  "104",
  "105",
  "108",
  "109",
  "110",
  "111",
  "112",
  "114",
  "115",
  "116",
  "117",
  "119",
];

export default async function (key?: string): Promise<string | undefined> {
  if (!key) {
    return (await import("resources/dictionaries/en/u.dic")).default;
  }

  switch (key) {
    case "97":
      return (await import("resources/dictionaries/en/u97.dic")).default;
    case "98":
      return (await import("resources/dictionaries/en/u98.dic")).default;
    case "99":
      return (await import("resources/dictionaries/en/u99.dic")).default;
    case "100":
      return (await import("resources/dictionaries/en/u100.dic")).default;
    case "101":
      return (await import("resources/dictionaries/en/u101.dic")).default;
    case "102":
      return (await import("resources/dictionaries/en/u102.dic")).default;
    case "103":
      return (await import("resources/dictionaries/en/u103.dic")).default;
    case "104":
      return (await import("resources/dictionaries/en/u104.dic")).default;
    case "105":
      return (await import("resources/dictionaries/en/u105.dic")).default;
    case "108":
      return (await import("resources/dictionaries/en/u108.dic")).default;
    case "109":
      return (await import("resources/dictionaries/en/u109.dic")).default;
    case "110":
      return (await import("resources/dictionaries/en/u110.dic")).default;
    case "111":
      return (await import("resources/dictionaries/en/u111.dic")).default;
    case "112":
      return (await import("resources/dictionaries/en/u112.dic")).default;
    case "114":
      return (await import("resources/dictionaries/en/u114.dic")).default;
    case "115":
      return (await import("resources/dictionaries/en/u115.dic")).default;
    case "116":
      return (await import("resources/dictionaries/en/u116.dic")).default;
    case "117":
      return (await import("resources/dictionaries/en/u117.dic")).default;
    case "119":
      return (await import("resources/dictionaries/en/u119.dic")).default;
    default:
      return;
  }
}
