/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { LexboxAuthStatus } from "../models";
// @ts-ignore
import { LexboxProject } from "../models";
// @ts-ignore
import { Word } from "../models";
/**
 * LexboxApi - axios parameter creator
 * @export
 */
export const LexboxApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    generateLogin: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/v1/lexbox/login`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthStatus: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/v1/lexbox/auth-status`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} projectCode
     * @param {string} vernacularLang
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEntries: async (
      projectCode: string,
      vernacularLang: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectCode' is not null or undefined
      assertParamExists("getEntries", "projectCode", projectCode);
      // verify required parameter 'vernacularLang' is not null or undefined
      assertParamExists("getEntries", "vernacularLang", vernacularLang);
      const localVarPath = `/v1/lexbox/entries/{projectCode}/{vernacularLang}`
        .replace(`{${"projectCode"}}`, encodeURIComponent(String(projectCode)))
        .replace(
          `{${"vernacularLang"}}`,
          encodeURIComponent(String(vernacularLang))
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProjects: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/v1/lexbox/projects`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logOut: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/v1/lexbox/logout`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * LexboxApi - functional programming interface
 * @export
 */
export const LexboxApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = LexboxApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async generateLogin(
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.generateLogin(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAuthStatus(
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<LexboxAuthStatus>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getAuthStatus(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {string} projectCode
     * @param {string} vernacularLang
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getEntries(
      projectCode: string,
      vernacularLang: string,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Word>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getEntries(
        projectCode,
        vernacularLang,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getProjects(
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<LexboxProject>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getProjects(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async logOut(
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.logOut(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * LexboxApi - factory interface
 * @export
 */
export const LexboxApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = LexboxApiFp(configuration);
  return {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    generateLogin(options?: any): AxiosPromise<void> {
      return localVarFp
        .generateLogin(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthStatus(options?: any): AxiosPromise<LexboxAuthStatus> {
      return localVarFp
        .getAuthStatus(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} projectCode
     * @param {string} vernacularLang
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getEntries(
      projectCode: string,
      vernacularLang: string,
      options?: any
    ): AxiosPromise<Array<Word>> {
      return localVarFp
        .getEntries(projectCode, vernacularLang, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProjects(options?: any): AxiosPromise<Array<LexboxProject>> {
      return localVarFp
        .getProjects(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logOut(options?: any): AxiosPromise<void> {
      return localVarFp
        .logOut(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for getEntries operation in LexboxApi.
 * @export
 * @interface LexboxApiGetEntriesRequest
 */
export interface LexboxApiGetEntriesRequest {
  /**
   *
   * @type {string}
   * @memberof LexboxApiGetEntries
   */
  readonly projectCode: string;

  /**
   *
   * @type {string}
   * @memberof LexboxApiGetEntries
   */
  readonly vernacularLang: string;
}

/**
 * LexboxApi - object-oriented interface
 * @export
 * @class LexboxApi
 * @extends {BaseAPI}
 */
export class LexboxApi extends BaseAPI {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LexboxApi
   */
  public generateLogin(options?: any) {
    return LexboxApiFp(this.configuration)
      .generateLogin(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LexboxApi
   */
  public getAuthStatus(options?: any) {
    return LexboxApiFp(this.configuration)
      .getAuthStatus(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {LexboxApiGetEntriesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LexboxApi
   */
  public getEntries(
    requestParameters: LexboxApiGetEntriesRequest,
    options?: any
  ) {
    return LexboxApiFp(this.configuration)
      .getEntries(
        requestParameters.projectCode,
        requestParameters.vernacularLang,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LexboxApi
   */
  public getProjects(options?: any) {
    return LexboxApiFp(this.configuration)
      .getProjects(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LexboxApi
   */
  public logOut(options?: any) {
    return LexboxApiFp(this.configuration)
      .logOut(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
