/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { FileStream } from "../models";
/**
 * LiftApi - axios parameter creator
 * @export
 */
export const LiftApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftCheckGet: async (
      projectId: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectId' is not null or undefined
      assertParamExists(
        "v1ProjectsProjectIdLiftCheckGet",
        "projectId",
        projectId
      );
      const localVarPath = `/v1/projects/{projectId}/lift/check`.replace(
        `{${"projectId"}}`,
        encodeURIComponent(String(projectId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftDeleteexportGet: async (
      projectId: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectId' is not null or undefined
      assertParamExists(
        "v1ProjectsProjectIdLiftDeleteexportGet",
        "projectId",
        projectId
      );
      const localVarPath = `/v1/projects/{projectId}/lift/deleteexport`.replace(
        `{${"projectId"}}`,
        encodeURIComponent(String(projectId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftDownloadGet: async (
      projectId: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectId' is not null or undefined
      assertParamExists(
        "v1ProjectsProjectIdLiftDownloadGet",
        "projectId",
        projectId
      );
      const localVarPath = `/v1/projects/{projectId}/lift/download`.replace(
        `{${"projectId"}}`,
        encodeURIComponent(String(projectId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftExportGet: async (
      projectId: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectId' is not null or undefined
      assertParamExists(
        "v1ProjectsProjectIdLiftExportGet",
        "projectId",
        projectId
      );
      const localVarPath = `/v1/projects/{projectId}/lift/export`.replace(
        `{${"projectId"}}`,
        encodeURIComponent(String(projectId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} projectId
     * @param {any} file
     * @param {string} name
     * @param {string} filePath
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftUploadPost: async (
      projectId: string,
      file: any,
      name: string,
      filePath: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'projectId' is not null or undefined
      assertParamExists(
        "v1ProjectsProjectIdLiftUploadPost",
        "projectId",
        projectId
      );
      // verify required parameter 'file' is not null or undefined
      assertParamExists("v1ProjectsProjectIdLiftUploadPost", "file", file);
      // verify required parameter 'name' is not null or undefined
      assertParamExists("v1ProjectsProjectIdLiftUploadPost", "name", name);
      // verify required parameter 'filePath' is not null or undefined
      assertParamExists(
        "v1ProjectsProjectIdLiftUploadPost",
        "filePath",
        filePath
      );
      const localVarPath = `/v1/projects/{projectId}/lift/upload`.replace(
        `{${"projectId"}}`,
        encodeURIComponent(String(projectId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;
      const localVarFormParams = new ((configuration &&
        configuration.formDataCtor) ||
        FormData)();

      if (file !== undefined) {
        localVarFormParams.append("File", file as any);
      }

      if (name !== undefined) {
        localVarFormParams.append("Name", name as any);
      }

      if (filePath !== undefined) {
        localVarFormParams.append("FilePath", filePath as any);
      }

      localVarHeaderParameter["Content-Type"] = "multipart/form-data";

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = localVarFormParams;

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * LiftApi - functional programming interface
 * @export
 */
export const LiftApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = LiftApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v1ProjectsProjectIdLiftCheckGet(
      projectId: string,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.v1ProjectsProjectIdLiftCheckGet(
        projectId,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v1ProjectsProjectIdLiftDeleteexportGet(
      projectId: string,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.v1ProjectsProjectIdLiftDeleteexportGet(
        projectId,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v1ProjectsProjectIdLiftDownloadGet(
      projectId: string,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileStream>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.v1ProjectsProjectIdLiftDownloadGet(
        projectId,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v1ProjectsProjectIdLiftExportGet(
      projectId: string,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.v1ProjectsProjectIdLiftExportGet(
        projectId,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {string} projectId
     * @param {any} file
     * @param {string} name
     * @param {string} filePath
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async v1ProjectsProjectIdLiftUploadPost(
      projectId: string,
      file: any,
      name: string,
      filePath: string,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.v1ProjectsProjectIdLiftUploadPost(
        projectId,
        file,
        name,
        filePath,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * LiftApi - factory interface
 * @export
 */
export const LiftApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = LiftApiFp(configuration);
  return {
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftCheckGet(
      projectId: string,
      options?: any
    ): AxiosPromise<boolean> {
      return localVarFp
        .v1ProjectsProjectIdLiftCheckGet(projectId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftDeleteexportGet(
      projectId: string,
      options?: any
    ): AxiosPromise<string> {
      return localVarFp
        .v1ProjectsProjectIdLiftDeleteexportGet(projectId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftDownloadGet(
      projectId: string,
      options?: any
    ): AxiosPromise<FileStream> {
      return localVarFp
        .v1ProjectsProjectIdLiftDownloadGet(projectId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} projectId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftExportGet(
      projectId: string,
      options?: any
    ): AxiosPromise<string> {
      return localVarFp
        .v1ProjectsProjectIdLiftExportGet(projectId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} projectId
     * @param {any} file
     * @param {string} name
     * @param {string} filePath
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    v1ProjectsProjectIdLiftUploadPost(
      projectId: string,
      file: any,
      name: string,
      filePath: string,
      options?: any
    ): AxiosPromise<number> {
      return localVarFp
        .v1ProjectsProjectIdLiftUploadPost(
          projectId,
          file,
          name,
          filePath,
          options
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for v1ProjectsProjectIdLiftCheckGet operation in LiftApi.
 * @export
 * @interface LiftApiV1ProjectsProjectIdLiftCheckGetRequest
 */
export interface LiftApiV1ProjectsProjectIdLiftCheckGetRequest {
  /**
   *
   * @type {string}
   * @memberof LiftApiV1ProjectsProjectIdLiftCheckGet
   */
  readonly projectId: string;
}

/**
 * Request parameters for v1ProjectsProjectIdLiftDeleteexportGet operation in LiftApi.
 * @export
 * @interface LiftApiV1ProjectsProjectIdLiftDeleteexportGetRequest
 */
export interface LiftApiV1ProjectsProjectIdLiftDeleteexportGetRequest {
  /**
   *
   * @type {string}
   * @memberof LiftApiV1ProjectsProjectIdLiftDeleteexportGet
   */
  readonly projectId: string;
}

/**
 * Request parameters for v1ProjectsProjectIdLiftDownloadGet operation in LiftApi.
 * @export
 * @interface LiftApiV1ProjectsProjectIdLiftDownloadGetRequest
 */
export interface LiftApiV1ProjectsProjectIdLiftDownloadGetRequest {
  /**
   *
   * @type {string}
   * @memberof LiftApiV1ProjectsProjectIdLiftDownloadGet
   */
  readonly projectId: string;
}

/**
 * Request parameters for v1ProjectsProjectIdLiftExportGet operation in LiftApi.
 * @export
 * @interface LiftApiV1ProjectsProjectIdLiftExportGetRequest
 */
export interface LiftApiV1ProjectsProjectIdLiftExportGetRequest {
  /**
   *
   * @type {string}
   * @memberof LiftApiV1ProjectsProjectIdLiftExportGet
   */
  readonly projectId: string;
}

/**
 * Request parameters for v1ProjectsProjectIdLiftUploadPost operation in LiftApi.
 * @export
 * @interface LiftApiV1ProjectsProjectIdLiftUploadPostRequest
 */
export interface LiftApiV1ProjectsProjectIdLiftUploadPostRequest {
  /**
   *
   * @type {string}
   * @memberof LiftApiV1ProjectsProjectIdLiftUploadPost
   */
  readonly projectId: string;

  /**
   *
   * @type {any}
   * @memberof LiftApiV1ProjectsProjectIdLiftUploadPost
   */
  readonly file: any;

  /**
   *
   * @type {string}
   * @memberof LiftApiV1ProjectsProjectIdLiftUploadPost
   */
  readonly name: string;

  /**
   *
   * @type {string}
   * @memberof LiftApiV1ProjectsProjectIdLiftUploadPost
   */
  readonly filePath: string;
}

/**
 * LiftApi - object-oriented interface
 * @export
 * @class LiftApi
 * @extends {BaseAPI}
 */
export class LiftApi extends BaseAPI {
  /**
   *
   * @param {LiftApiV1ProjectsProjectIdLiftCheckGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LiftApi
   */
  public v1ProjectsProjectIdLiftCheckGet(
    requestParameters: LiftApiV1ProjectsProjectIdLiftCheckGetRequest,
    options?: any
  ) {
    return LiftApiFp(this.configuration)
      .v1ProjectsProjectIdLiftCheckGet(requestParameters.projectId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {LiftApiV1ProjectsProjectIdLiftDeleteexportGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LiftApi
   */
  public v1ProjectsProjectIdLiftDeleteexportGet(
    requestParameters: LiftApiV1ProjectsProjectIdLiftDeleteexportGetRequest,
    options?: any
  ) {
    return LiftApiFp(this.configuration)
      .v1ProjectsProjectIdLiftDeleteexportGet(
        requestParameters.projectId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {LiftApiV1ProjectsProjectIdLiftDownloadGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LiftApi
   */
  public v1ProjectsProjectIdLiftDownloadGet(
    requestParameters: LiftApiV1ProjectsProjectIdLiftDownloadGetRequest,
    options?: any
  ) {
    return LiftApiFp(this.configuration)
      .v1ProjectsProjectIdLiftDownloadGet(requestParameters.projectId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {LiftApiV1ProjectsProjectIdLiftExportGetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LiftApi
   */
  public v1ProjectsProjectIdLiftExportGet(
    requestParameters: LiftApiV1ProjectsProjectIdLiftExportGetRequest,
    options?: any
  ) {
    return LiftApiFp(this.configuration)
      .v1ProjectsProjectIdLiftExportGet(requestParameters.projectId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {LiftApiV1ProjectsProjectIdLiftUploadPostRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LiftApi
   */
  public v1ProjectsProjectIdLiftUploadPost(
    requestParameters: LiftApiV1ProjectsProjectIdLiftUploadPostRequest,
    options?: any
  ) {
    return LiftApiFp(this.configuration)
      .v1ProjectsProjectIdLiftUploadPost(
        requestParameters.projectId,
        requestParameters.file,
        requestParameters.name,
        requestParameters.filePath,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
