/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DomainSenseUserCount
 */
export interface DomainSenseUserCount {
  /**
   *
   * @type {string}
   * @memberof DomainSenseUserCount
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof DomainSenseUserCount
   */
  username?: string | null;
  /**
   *
   * @type {Set<string>}
   * @memberof DomainSenseUserCount
   */
  domainSet: Set<string>;
  /**
   *
   * @type {number}
   * @memberof DomainSenseUserCount
   */
  domainCount?: number;
  /**
   *
   * @type {number}
   * @memberof DomainSenseUserCount
   */
  senseCount?: number;
}
