/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectWritingSystemsDto } from "./project-writing-systems-dto";

/**
 *
 * @export
 * @interface FlexProjectMetadataDto
 */
export interface FlexProjectMetadataDto {
  /**
   *
   * @type {string}
   * @memberof FlexProjectMetadataDto
   */
  projectId?: string;
  /**
   *
   * @type {number}
   * @memberof FlexProjectMetadataDto
   */
  lexEntryCount?: number | null;
  /**
   *
   * @type {string}
   * @memberof FlexProjectMetadataDto
   */
  langProjectId?: string | null;
  /**
   *
   * @type {number}
   * @memberof FlexProjectMetadataDto
   */
  flexModelVersion?: number | null;
  /**
   *
   * @type {ProjectWritingSystemsDto}
   * @memberof FlexProjectMetadataDto
   */
  writingSystems?: ProjectWritingSystemsDto;
}
