/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LexboxPartOfSpeech
 */
export interface LexboxPartOfSpeech {
  /**
   *
   * @type {string}
   * @memberof LexboxPartOfSpeech
   */
  id?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof LexboxPartOfSpeech
   */
  name?: { [key: string]: string } | null;
}
