/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlexProjectMetadataDto } from "./flex-project-metadata-dto";

/**
 *
 * @export
 * @interface LexboxProject
 */
export interface LexboxProject {
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  parentId?: string | null;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  code?: string | null;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  retentionPolicy?: string | null;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  type?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof LexboxProject
   */
  isConfidential?: boolean | null;
  /**
   *
   * @type {number}
   * @memberof LexboxProject
   */
  repoSizeInKb?: number | null;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  resetStatus?: string | null;
  /**
   *
   * @type {string}
   * @memberof LexboxProject
   */
  projectOrigin?: string | null;
  /**
   *
   * @type {number}
   * @memberof LexboxProject
   */
  userCount?: number;
  /**
   *
   * @type {FlexProjectMetadataDto}
   * @memberof LexboxProject
   */
  flexProjectMetadata?: FlexProjectMetadataDto;
}
