/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MergeWordSetEntry
 */
export interface MergeWordSetEntry {
  /**
   *
   * @type {string}
   * @memberof MergeWordSetEntry
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof MergeWordSetEntry
   */
  projectId?: string | null;
  /**
   *
   * @type {string}
   * @memberof MergeWordSetEntry
   */
  userId?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof MergeWordSetEntry
   */
  wordIds?: Array<string> | null;
}
