/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SemanticDomainTimestampNode
 */
export interface SemanticDomainTimestampNode {
  /**
   *
   * @type {string}
   * @memberof SemanticDomainTimestampNode
   */
  shortDateString: string;
  /**
   *
   * @type {number}
   * @memberof SemanticDomainTimestampNode
   */
  hour: number;
  /**
   *
   * @type {number}
   * @memberof SemanticDomainTimestampNode
   */
  count: number;
  /**
   *
   * @type {Array<SemanticDomainTimestampNode>}
   * @memberof SemanticDomainTimestampNode
   */
  nodeList: Array<SemanticDomainTimestampNode>;
}
