/* tslint:disable */
/* eslint-disable */
/**
 * BackendFramework
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Consent } from "./consent";

/**
 *
 * @export
 * @interface Speaker
 */
export interface Speaker {
  /**
   *
   * @type {string}
   * @memberof Speaker
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Speaker
   */
  projectId: string;
  /**
   *
   * @type {string}
   * @memberof Speaker
   */
  name: string;
  /**
   *
   * @type {Consent}
   * @memberof Speaker
   */
  consent: Consent;
}
