{{- if and .Values.certManager.enabled (eq .Values.certManager.certIssuer "self-signed") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
{{- end }}
