---
install_credential_helper: false
credential_helper_version: v0.6.3

docker_packages:
  amd64:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  arm64:
    - docker
    - docker.io
    - docker-compose
