name: commit-message-lint

on:
  pull_request:
    branches: [master]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

permissions:
  contents: read

jobs:
  commit-message-lint:
    permissions:
      contents: read
      pull-requests: write
    uses: sillsdev/FieldWorks/.github/workflows/CommitMessage.yml@fb4c99d89f4574ac648e3445192ad7e667dcef0f
