name: installer_release

on:
  workflow_dispatch:
    inputs:
      confirm_upload:
        description: "Type UP to confirm installer upload"
        required: true
        default: ""
  workflow_run:
    workflows: ["Deploy Update to Live Server"]
    types:
      - completed

permissions:
  contents: read

jobs:
  make_installer:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    outputs:
      release_tag: ${{ steps.release.outputs.tag }}
    steps:
      # See https://docs.stepsecurity.io/harden-runner/getting-started/ for instructions on
      # configuring harden-runner and identifying allowed endpoints.
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: block
          allowed-endpoints: >
            *-docker.pkg.dev:443
            *.cloudfront.net:443
            api.github.com:443
            azure.archive.ubuntu.com:80
            cdn.dl.k8s.io:443
            dl.k8s.io:443
            esm.ubuntu.com:443
            files.pythonhosted.org:443
            get.helm.sh:443
            get.k3s.io:443
            github.com:443
            kubernetes.github.io:443
            packages.microsoft.com:443
            prod-registry-k8s-io-us-east-1.s3.dualstack.us-east-1.amazonaws.com:443
            prod-registry-k8s-io-us-east-2.s3.dualstack.us-east-2.amazonaws.com:443
            prod-registry-k8s-io-us-west-1.s3.dualstack.us-west-1.amazonaws.com:443
            prod-registry-k8s-io-us-west-2.s3.dualstack.us-west-2.amazonaws.com:443
            public.ecr.aws:443
            pypi.org:443
            registry.k8s.io:443
            release-assets.githubusercontent.com:443
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y makeself
        shell: bash
      - name: Get latest release tag
        env:
          GH_TOKEN: ${{ github.token }}
        id: release
        run: |
          echo "tag=$(gh release view --json tagName -q .tagName)" >> $GITHUB_OUTPUT
      - name: Make installer with release version
        run: |
          cd installer
          ./make-combine-installer.sh ${{ steps.release.outputs.tag }} --debug
        shell: bash
      - name: Upload installer artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: combine-installer
          path: installer/combine-installer.run
          retention-days: 5

  upload_installer:
    needs: make_installer
    if: github.event_name == 'workflow_run' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_upload == 'UP')
    runs-on: ubuntu-latest
    steps:
      # See https://docs.stepsecurity.io/harden-runner/getting-started/ for instructions on
      # configuring harden-runner and identifying allowed endpoints.
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            s3.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com:443
            sts.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com:443
      - name: Download installer artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: combine-installer
          path: installer/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Upload installer to S3
        run: |
          TARGET=s3://software.thecombine.app/combine-installer-${{ needs.make_installer.outputs.release_tag }}.run
          aws s3 cp installer/combine-installer.run $TARGET --content-type application/octet-stream
        shell: bash
