// This file was generated by `python scripts/split_dictionary.py -l pt -t 2000 -T 20000 -m 8`.

export const keys = [
  "97",
  "97-98",
  "97-99",
  "97-100",
  "97-102",
  "97-103",
  "97-108",
  "97-109",
  "97-110",
  "97-112",
  "97-114",
  "97-116",
  "98",
  "99",
  "99-97",
  "99-101",
  "99-104",
  "99-105",
  "99-111",
  "99-117",
  "100",
  "101",
  "101-109",
  "101-110",
  "101-115",
  "101-120",
  "102",
  "103",
  "104",
  "105",
  "106",
  "108",
  "109",
  "109-97",
  "109-101",
  "109-105",
  "109-111",
  "109-117",
  "110",
  "111",
  "112",
  "112-97",
  "112-101",
  "112-105",
  "112-111",
  "112-114",
  "114",
  "114-97",
  "114-101",
  "114-111",
  "115",
  "116",
  "117",
  "118",
  "122",
];

export default async function (key?: string): Promise<string | undefined> {
  if (!key) {
    return (await import("resources/dictionaries/pt/u.dic")).default;
  }

  switch (key) {
    case "97":
      return (await import("resources/dictionaries/pt/u97.dic")).default;
    case "97-98":
      return (await import("resources/dictionaries/pt/u97-98.dic")).default;
    case "97-99":
      return (await import("resources/dictionaries/pt/u97-99.dic")).default;
    case "97-100":
      return (await import("resources/dictionaries/pt/u97-100.dic")).default;
    case "97-102":
      return (await import("resources/dictionaries/pt/u97-102.dic")).default;
    case "97-103":
      return (await import("resources/dictionaries/pt/u97-103.dic")).default;
    case "97-108":
      return (await import("resources/dictionaries/pt/u97-108.dic")).default;
    case "97-109":
      return (await import("resources/dictionaries/pt/u97-109.dic")).default;
    case "97-110":
      return (await import("resources/dictionaries/pt/u97-110.dic")).default;
    case "97-112":
      return (await import("resources/dictionaries/pt/u97-112.dic")).default;
    case "97-114":
      return (await import("resources/dictionaries/pt/u97-114.dic")).default;
    case "97-116":
      return (await import("resources/dictionaries/pt/u97-116.dic")).default;
    case "98":
      return (await import("resources/dictionaries/pt/u98.dic")).default;
    case "99":
      return (await import("resources/dictionaries/pt/u99.dic")).default;
    case "99-97":
      return (await import("resources/dictionaries/pt/u99-97.dic")).default;
    case "99-101":
      return (await import("resources/dictionaries/pt/u99-101.dic")).default;
    case "99-104":
      return (await import("resources/dictionaries/pt/u99-104.dic")).default;
    case "99-105":
      return (await import("resources/dictionaries/pt/u99-105.dic")).default;
    case "99-111":
      return (await import("resources/dictionaries/pt/u99-111.dic")).default;
    case "99-117":
      return (await import("resources/dictionaries/pt/u99-117.dic")).default;
    case "100":
      return (await import("resources/dictionaries/pt/u100.dic")).default;
    case "101":
      return (await import("resources/dictionaries/pt/u101.dic")).default;
    case "101-109":
      return (await import("resources/dictionaries/pt/u101-109.dic")).default;
    case "101-110":
      return (await import("resources/dictionaries/pt/u101-110.dic")).default;
    case "101-115":
      return (await import("resources/dictionaries/pt/u101-115.dic")).default;
    case "101-120":
      return (await import("resources/dictionaries/pt/u101-120.dic")).default;
    case "102":
      return (await import("resources/dictionaries/pt/u102.dic")).default;
    case "103":
      return (await import("resources/dictionaries/pt/u103.dic")).default;
    case "104":
      return (await import("resources/dictionaries/pt/u104.dic")).default;
    case "105":
      return (await import("resources/dictionaries/pt/u105.dic")).default;
    case "106":
      return (await import("resources/dictionaries/pt/u106.dic")).default;
    case "108":
      return (await import("resources/dictionaries/pt/u108.dic")).default;
    case "109":
      return (await import("resources/dictionaries/pt/u109.dic")).default;
    case "109-97":
      return (await import("resources/dictionaries/pt/u109-97.dic")).default;
    case "109-101":
      return (await import("resources/dictionaries/pt/u109-101.dic")).default;
    case "109-105":
      return (await import("resources/dictionaries/pt/u109-105.dic")).default;
    case "109-111":
      return (await import("resources/dictionaries/pt/u109-111.dic")).default;
    case "109-117":
      return (await import("resources/dictionaries/pt/u109-117.dic")).default;
    case "110":
      return (await import("resources/dictionaries/pt/u110.dic")).default;
    case "111":
      return (await import("resources/dictionaries/pt/u111.dic")).default;
    case "112":
      return (await import("resources/dictionaries/pt/u112.dic")).default;
    case "112-97":
      return (await import("resources/dictionaries/pt/u112-97.dic")).default;
    case "112-101":
      return (await import("resources/dictionaries/pt/u112-101.dic")).default;
    case "112-105":
      return (await import("resources/dictionaries/pt/u112-105.dic")).default;
    case "112-111":
      return (await import("resources/dictionaries/pt/u112-111.dic")).default;
    case "112-114":
      return (await import("resources/dictionaries/pt/u112-114.dic")).default;
    case "114":
      return (await import("resources/dictionaries/pt/u114.dic")).default;
    case "114-97":
      return (await import("resources/dictionaries/pt/u114-97.dic")).default;
    case "114-101":
      return (await import("resources/dictionaries/pt/u114-101.dic")).default;
    case "114-111":
      return (await import("resources/dictionaries/pt/u114-111.dic")).default;
    case "115":
      return (await import("resources/dictionaries/pt/u115.dic")).default;
    case "116":
      return (await import("resources/dictionaries/pt/u116.dic")).default;
    case "117":
      return (await import("resources/dictionaries/pt/u117.dic")).default;
    case "118":
      return (await import("resources/dictionaries/pt/u118.dic")).default;
    case "122":
      return (await import("resources/dictionaries/pt/u122.dic")).default;
    default:
      return undefined;
    }
}
